services:
  german-sentiment-service:
    build: .
    image: "german-sentiment-service-local"
    command: uvicorn german_sentiment_service.app:app --reload --host 0.0.0.0 --port 8000
    ports:
      - 8001:8000
    volumes:
      - ".:/app"
  german-sentiment-service-test:
    build: .
    image: "german-sentiment-service-local"
    command: pytest tests
    ports:
      - 8002:8000
    volumes:
      - ".:/app"


