services:
  german-sentiment-service:
    build: .
    image: "german-sentiment-service-local"
    command: uvicorn app:app --reload --host 0.0.0.0 --port 8000
    ports:
      - 8001:8000
    volumes:
      - "./german_sentiment_service:/app"


